### ISSUE TITLE
古川陽介さんへ

### ISSUE THREAD

**Issue by takuyatahata** [yosuke-furukawa/leets#1]
@yosuke-furukawa 　さんへ
web＋databaseの今月号にあなたの記事が載っていますが、user: yosuke-tfurukawaで検索しても出てきません。雑誌の表記が間違えているのかもしれませんので連絡しました。

**Comment by yosuke-furukawa** [comment]
おお、ほんとだ、、、間違ってますね。誤植の指摘、ありがとうございます。連絡しておきます。

**Comment by yosuke-furukawa** [comment]
一旦クローズします！

**Comment by yosuke-furukawa** [comment]
更新してもらいました。

https://gihyo.jp/magazine/wdpress/archive/2020/vol118/support#supportApology
